import {Itinerary, TodoType, TransportationType} from "@/app/itinerary/_utils/typings"

export const Data: Itinerary = {
    id: "itinerary_001",
    title: "Liburan ke Bali",
    userOwner: "user_123",
    userAccess: ["user_456", "user_789"],
    totalCost: 3500000,
    description: "Liburan selama 3 hari di Bali dengan teman-teman.",
    createdAt: new Date("2025-05-01"),
    imageCover: "https://example.com/bali.jpg",
    tag: ["beach", "relaxing", "culture"],
    Cities: [
      {
        cityId: 1,
        cityName: "Denpasar",
      },
      {
        cityId: 2,
        cityName: "Ubud",
      },
    ],
    dateStart: new Date("2025-06-10"),
    dateEnd: new Date("2025-06-12"),
    itineraries: [
      {
        id_order_day: 1,
        day: 1,
        date: new Date("2025-06-10"),
        city: { cityId: 1, cityName: "Denpasar" },
        todos: [
          {
            id_order_todo: 1,
            id_hotel: "hotel_01",
            nameTodo: "Check-in Hotel Mercure",
            typeTodo: "hotel",
            hotelName: "Hotel Mercure Bali",
            checkInTime: "14:00",
            checkOutTime: "12:00",
            isPayable: true,
            cost: 800000,
            imgTodoUrl: "https://example.com/hotel.jpg",
          },
          {
            id_order_todo: 2,
            id_activity: "activity_01",
            nameTodo: "Berenang di Pantai Kuta",
            typeTodo: "activity",
            time_start: "16:00",
            time_end: "18:00",
            location: "Pantai Kuta",
            isPayable: false,
            imgTodoUrl: "https://example.com/beach.jpg",
          },
          {
            id_order_todo: 3,
            nameTodo: "Naik GrabBike ke hotel",
            typeTodo: "transportation",
            departureTime: "18:30",
            arrivalTime: "18:50",
            range: "3 km",
            transportType: "ride_hailing_bike",
            origin: "Pantai Kuta",
            destination: "Hotel Mercure",
            isPayable: true,
            cost: 15000,
            imgTodoUrl: "https://example.com/grabbike.jpg",
          },
        ],
      },
      {
        id_order_day: 2,
        day: 2,
        date: new Date("2025-06-11"),
        city: { cityId: 2, cityName: "Ubud" },
        todos: [
          {
            id_order_todo: 4,
            id_activity: "activity_02",
            nameTodo: "Mengunjungi Monkey Forest",
            typeTodo: "activity",
            time_start: "10:00",
            time_end: "12:00",
            location: "Ubud Monkey Forest",
            isPayable: true,
            cost: 50000,
            imgTodoUrl: "https://example.com/monkeyforest.jpg",
          },
          {
            id_order_todo: 5,
            nameTodo: "Naik mobil ke Ubud",
            typeTodo: "transportation",
            departureTime: "08:00",
            arrivalTime: "09:30",
            range: "40 km",
            transportType: "ride_hailing_car",
            origin: "Denpasar",
            destination: "Ubud",
            isPayable: true,
            cost: 120000,
            imgTodoUrl: "https://example.com/car.jpg",
          },
        ],
      },
    ],
  };
  