export const TypeList = [
    'Hotel',
    'Resort',
    'Villa',
    'Apartment/Flat',
    'Homestay',
    'Entire House'
]
export const StateList = [
    'D.I. Yogyakarta', 'Bali', 'East Java', 'DKI Jakarta', 'Riau Islands', 'West Nusa Tenggara',    
    'Banten', 'West Java', 'North Sumatera', 'North Sulawesi', 'South Sulawesi', 'Central Java', 'East Kalimantan', 'Riau', 
    'Lampung', 'West Sumatera', 'South Sumatera', 'Aceh', 'Papua', 'Central Sulawesi', 'North Kalimantan', 'South Kalimantan', 
    'West Kalimantan', 'East Nusa Tenggara', 'Jambi', 'Maluku', 'Central Kalimantan', 'South East Sulawesi', 'Bangka Belitung Islands', 
    'Bengkulu', 'West Papua', 'Gorontalo', 'BALI', 'Yogyakarta', 'Jakarta', 'Bangka-Belitung', 'North Maluku', 'West Sulawesi',
]
export const CityList = [
    'Yogyakarta', 'Bali', 'Surabaya', 'Jakarta', 'Bintan Island', 'Lombok', 'Tangerang', 'Bandung', 'Batam Island', 'Medan', 'Manado', 'Makassar', 
    'Malang', 'Semarang', 'Magelang', 'Bogor', 'Samarinda', 'Surakarta', 'Pekanbaru', 'Cirebon', 'Bandar Lampung', 'Mengkendek', 'Bekasi', 'Anyer', 'Parapat', 
    'Berastagi', 'Bukittinggi', 'Padang', 'Palembang', 'Trawas', 'Blitar', 'Pelabuhan Ratu', 'Balikpapan', 'Bromo', 'Aceh', 'Irian Jaya / Papua', 'Puncak', 
    'Banyuwangi', 'Palu', 'Tarakan', 'Banjarmasin', 'Pontianak', 'Labuan Bajo', 'Cikarang', 'Serang', 'Banten', 'Kediri', 'Jambi', 'Ambon', 'Sungai Sekonyer',
    'Ende', 'Kupang', 'Flores', 'Kendari', 'Palangkaraya', 'Belitung', 'Bangka', 'Pangandaran', 'Sumbawa', 'Pekalongan', 'Karawang', 'Jember', 'Bengkulu', 'Garut',
    'Tawangmangu', 'Bondowoso', 'Purwakarta', 'Dumai', 'Tulungagung', 'Madiun', 'Cepu', 'Rantepao', 'Sawahlunto', 'Kudus', 'Pacitan', 'Salatiga', 'Parepare', 'Sorong',
    'Banjarbaru', 'Gorontalo', 'Merauke', 'Tasikmalaya', 'Sarolangun', 'Kalianda', 'Sungai Liat', 'Tegal', 'Duri', 'Tentena', 'Panawuan', 'Cilacap', 'Pangkalanbuun',
    'Pemalang', 'Ponorogo', 'Tanjung', 'Goron Talo', 'Purwokerto', 'Pasuruan', 'Samosir', 'Probolinggo', 'Wonosobo', 'Nemberala', 'Sukaresik', 'Ujung Genteng', 'Klaten',
    'Jepara', 'Boyolali', 'Ciamis', 'Padang Sidempuan', 'Tarutung', 'Sibolga', 'Jombang', 'Pematangsiantar', 'Tambolaka', 'Lubuklinggau', 'Timika', 'Karimunjawa',
    'Wangiwangi Island', 'Baturaja', 'Sukabumi', 'Raja Ampat', 'Martapura', 'Bojonegoro', 'Depok', 'Ruteng', 'Lahat', 'Waigete', 'Salahutu', 'Merek', 'Mojokerto',
    'Singkawang', 'Binjai', 'Bone', 'Tanjung Balai Karimun', 'Pandeglang', 'Tuban', 'Tanete', 'Demak', 'Karangtanjung', 'Batulicin', 'Berau', 'Cibeureum', 'Rembang',
    'Ketapang', 'Kastela', 'Tanjung Selor', 'Paiton', 'Rantauprapat', 'Labuhanpandan', 'Purbalingga', 'Banjarnegara', 'Lumajang', 'Bitung', 'Bukit Lawang', 'Sampit',
    'Tana Paser', 'Deli Serdang', 'Tanjung Redeb', 'Sumba Island', 'Muara Enim', 'Watukarung', 'Pati', 'Ternate', 'Kuningan', 'Oenggaut', 'Likupang', 'Gunung Putri',
    'Madura Island', 'Huu', 'Kotamobagu', 'Singa Gembara', 'Purwodadi', 'Langgur', 'Paciran', 'Pondang', 'Luwuk', 'Kebumen', 'Sekongkang Bawah', 'Cianjur', 'Majalengka',
    'Waingapu', 'Karangturi', 'Macanang', 'Gunung Bahagia', 'Songgom', 'Lembar', 'Gunungsitoli', 'Bedoyo', 'Kalegowa', 'Brebes', 'Aek Tolang', 'Dieng Kulong', 'Botohilitano',
    'Sumberagung', 'Ambarawa', 'Buwun Mas', 'Mangkung', 'Sragen', 'Wula Waiijelu', 'Baubau', 'Saleman', 'Ampana', 'Maumere', 'Simeulue Island', 'Tanjung Balai', 'Boa', 'Karanganyar',
    'Kendal', 'Beru', 'Gresik', 'Tebing Tinggi', 'Balige', 'Rinondoran', 'Tana Toraja', 'Seloliman', 'Sampe Raya', 'North Tapanuli', 'Nganjuk', 'Pulau Una Una', 'Taubneno', 
    'Tanjung Pude', 'Bagan Batu', 'Slawi', 'Bambu', 'Meulaboh', 'Nangamese', 'Kebonkacang', 'Namu Sialang', 'Moyo Island', 'Sigunturmuda', 'Sarongan', 'Lifao', 'Gaura', 'Gedung', 
    'Siborongborong', 'Membalong', 'Teluk Dalam', 'Maratua Teluk Harapan', 'Langsa', 'Mekar Sari', 'Kabil', 'Sarangan', 'Pagerharjo', 'Mancagahar', 'Cikande', 'Ngargosari', 
    'Sendangagung', 'Matanurung', 'Kasang', 'Palopo', 'Kisaran', 'Patiala Bawa', 'Mamuju', 'Tinggimoncong', 'Bahapal Raya', 'Sidoarjo Regency', 'Lhokseumawe', 'Payakumbuh', 
    'Kutacane', 'Wakatobi', 'Indramayu', 'Sumedang', 'Hargowilis', 'Ngawi', 'Pesawaran Regency', 'Grajagan', 'Pagar Alam', 'Painan', 'Batusangkar', 'Sapit', 'Busung Indah', 
    'Maninjau', 'Benteng Selatan', 'Sarotari', 'Mentawai Island', 'Prabumulih', 'Utarom', 'Lamongan', 'Puspanegara', 'Sungai Danau', 'Sangkulirang', 'Bontang', 'Mentok', 
    'Maratua Payung-payung', 'Bau-Bau', 'Kepulauan Seribu', 'Manamas', 'Anambas Islands', 'Pulau Baguk', 'Naibos', 'Air Itam', 'Kuantan Singingi Regency', 'Kota Pari', 
    'Tembilahan Kota', 'Nabire', 'Babo', 'Magetan', 'Sungai Penuh', 'Bulak', 'Bintang', 'Kalibata', 'Karangkandri', 'Alor Island', 'Besar', 'Temanggung', 'Juanga', 'Bima', 
    'Pulo Indo', 'Merapi', 'Sendang', 'Agam', 'Situbondo', 'Patikraja', 'Sunggal', 'Cikampek', 'Pulau Derawan', 'Tanjung Morawa', 'Poso', 'Rejosari', 'Sumberejo', 'Setanggor', 
    'Blora', 'Sembulang', 'Buaran', 'Batang', 'Cisurupan', 'Waha', 'Wamena', 'Patikarya', 'Bantaeng', 'Tegalrejo', 'Takengon', 'Pangkalanjati', 'Sukamanah', 'Mayangan', 
    'Watu Nggene', 'Kampoti', 'Pinrang', 'Kandeman', 'Abadi', 'Malino', 'Cunca Wulang', 'Komodo', 'Tahuna', 'Babakan', 'Sidikalang', 'Banyubiru', 'Murni Jaya', 'Mabuun', 'Kolaka', 
    'Wajo', 'Liang Ndara', 'Long Wehea', 'Subang', 'Belimbing Baru', 'Sintang', 'Anggrek', 'Bua', 'Timbangan', 'Parigi Moutong Regency', 'Rokan Hulu Regency', 'Pulisan', 'Majene', 
    'Perjiwa', 'Kalinaun', 'Wonogiri', 'Krui', 'Bengkalis', 'Karang Tengah', 'Watulimo', 'Wapia Pia', 'Senduro', 'South Ogan Komering Ulu', 'Tanah Kongkong', 'Sumbermujur', 
    'Ngebel', 'Bireuen', 'Ogan Komering Ilir', 'Segaramakmur', 'Peresak', 'Manggar', 'Cimanggis', 'Kampungjawa', 'Banda Aceh', 'Dobo', 'Lebo', 'Tepas', 'Karangputat', 'Banjar', 
    'Purworejo', 'Saukabu', 'Labulia', 'Palayangan', 'Sebong Lagoi', 'Kutoarjo', 'East Halmahera Regency', 'Sei Pinang', 'Luwu Regency', 'Nunukan', 'Hutan', 'Solok', 'Sinjai', 
    'Tungkal', 'Bonto Lempangan', 'Belolaut', 'Badung', 'Sarilamak', 'Tabundung', 'Alor Besar', 'Pasakiat Teileleu', 'Tarantang', 'Saumlaki', 'Kamang Hilir', 'Renged', 
    'Kalembu Kaha', 'Jati', 'Samiran', 'Tana Tidung', 'Pelalawan', 'Kuang', 'Timbang Lawan', 'Rote Island', 'Bawu', 'Topoyo', 'Kuning', 'Purwosari', 'Sanggau', 'Kadumbul', 
    'Margomulyo', 'Polewali Mandar', 'Lubuk Kupang', 'Kembaran', 'Maluk', 'Sungkai', 'Batukaras', 'Pegatan Hulu', 'Siantan', 'Gununggeulis', 'Muaraenim', 'Bajawa', 'Magek', 'Melawi', 
    'Pangkal Pinang', 'Sukaresmi', 'Glagah Arum', 'Tembilahan Hilir', 'Donggala', 'Pasirlangu', 'Pasir Putih', 'Salenrang', 'Cikeasudik', 'Lebak', 'Poja', 'Cluring', 'Raha', 
    'Muaratewe', 'Banda Neira', 'Suela', 'Rantetayo', 'Kumai Hulu', 'Padurenan', 'Puput', 'Mon Ikeun', 'Cempakaputih', 'West Banyak Island']
